# III İşverenler ve İşletmeciler için bSTR BIM Teknik Şartname Rehberi {.unnumbered}

| | |
|-|--------------|
|**Hazırlayan:**| Standartlar & Yayınlar Çalışma Grubu |
|**Tarih:**|29.09.2023     |
|**Versiyon:**|00     |

&nbsp;

Bu bölüm sayısal olarak bilgilerin düzenlenmesi ve süreçlerin kurgulanmasıyla, projelerinin daha etkin bir şekilde yürütülüp, teslim edilmesini talep eden işverenler ve işletmeciler için hazırlanmıştır. Projenin başından itibaren, tedarik aşamasında sözleşme dahilinde ve proje sırasında talep edilen bilgi, belge ve süreçler tanımlanmıştır. BIM protokolü projenin başından itibaren TS EN ISO 19650 bilgi yönetimi süreçleriyle uyumlu olarak tüm paydaşlar için beklentileri ile kapsamlarını netleştiren süreç ve belgelerin oluşturulmasını sağlamaktadır. Ayrıca, yüklenici firmalar bu bölümü kendi proje kapsamlarında işveren tarafından hazırlanan bir BIM protokolü veya başka ilgili gereksinimlerin olmaması durumunda, sayısal bilgi üretimi ve teslim şartlarını sağlamak için veya işveren tarafından kapsamın tanımlanmasını sağlamak için bir referans olarak da kullanabilir.

&nbsp;

Editör
: Dr. Ahmet ÇITIPITIOĞLU, *bSTR Standartlar ve Yayınlar Çalışma Grubu Koordinatörü (TAV İnşaat)*

&nbsp;

**Katkıda Bulunanlar**

Çalışma grubu bünyesinde taslak hazırlanmasına destek olan ve hazırlanan taslaklara görüş, yorum ve tekliflerini ileten, konu hakkında
tecrübelerini paylaşan uzman gönüllülerimize teşekkür ederiz.

##### PROJE GELİŞTİRME ÇALIŞMA GRUBU İCRA KURULU
| | |
|---|---|
| Dr. Ahmet ÇITIPITIOĞLU, *TAV İnşaat* | Hasan Can ÖZDEMİR, *SmartBIM* |
| Yrd. Doç. Dr. Aslı Akçamete GÜNGÖR, *ODTÜ* |İbrahim Halil CANSEVEN, *NTT Mimarlık* |
| Aygen ERKAL, *Türkiye İMSAD* | Kaan TOZKOPARAN, *Yüksel Proje* |
| Bahadır DEMİRTAŞ, *Arup* | Osman ÖZKAN, *EAE Elektrik* |
| Berke ÇELİKEL, *Freelance* | Serdar BİRDEN, *BIMMade* |
| Cenk ÇETİN, *Dorçe* | Serhat KAŞ, *Yüksel Proje* |
| Daniel KAZADO, *ProCS* | Serkan ELİBOLLAR, *ProCS* |
| Dilistan Bozan, *Arup* | Sinan ALEMDAR, *EMAY* |
| Prof. Dr. Esin Ergen PEHLEVAN, *İTÜ* | Uğur KAYA, *EMAY* |
| Gizem YILDIRIM, *BIMCHief* | Utku BAŞYAZICI, *DoxaA87* |

&nbsp;

##### STANDARTLAR ve YAYINLAR ÇALIŞMA GRUBU İCRA KURULU
| | |
|---|---|
| Dr. Ahmet ÇITIPITIOĞLU, *TAV İnşaat* | Öncü Ceren Varol ALİCİK, *Sika* |
| Yrd. Doç. Dr. Aslı Akçamete GÜNGÖR, *ODTÜ* | Osman ÖZKAN, *EAE Elektrik* |
| Aygen ERKAL, *Türkiye İMSAD* | Prof. Dr. Salih OFLUOĞLU, *ABÜ* |
| Bahadır DEMİRTAŞ, *Arup* | Serdar BİRDEN, *BIMMade* |
| Behnam AGHBALİ, *Saina* | Serhat KAŞ, *Yüksel Proje* |
| Berke ÇELİKEL, *Freelance* |Serkan ELİBOLLAR, *ProCS* |
| Çağdaş Ilgaz ŞENEL, *Hilti* | Uğur KAYA, *Emay* |
| Prof. Dr. Esin Ergen PEHLEVAN, *İTÜ* | Utku BAŞYAZICI, *Doxa87* |
| İdris BAHADUR, *Saina* | Yudum DEMİRKOL, *Şişecam* |
| Melis ATAY, *Turner* | |

&nbsp;

**Görüş Verenler**

| | |
|---|---|
| Erhan ÇEKİN, *Emay* | Fatih KAYA, *Emay* |
