# BIM Uygulama Planı Şablonu {#sec-bim-şablonu}

##	Kapsam
BIM Uygulama Planı'nın hazırlanmasıyla ilgili proje kapsamındaki şartname ve sözleşme şartlarına dair açıklama girilecektir.

##	Kısaltmalar ve Tanımlar
BIM Uygulama Planı'nda geçen tüm kısaltmaların ve teknik terimlerin tanımı yapılmalıdır.

##	Proje Bilgisi
### Proje İsmi
Projenin sözleşmedeki ve/veya çizimlerdeki resmi ismi yazılacaktır.

### Proje Özeti
Proje hakkında genel bilgiler verilecektir. Proje çıktılarıyla birlikte inşaat kapsamı, süresi, yapılan işin boyutu, yapıların tarifi ve özellikleri özetlenecektir.

### Proje Paydaşları
Tüm proje paydaşları listelenecektir: İşveren, işveren temsilcileri, müşavir firmalar, ana müteahhit v.b.

### Proje Süresi ve Hedef Tarihler
Sözleşmede belirtilen proje süresi ile belirtilen ana terminler listelenecektir.

## Projedeki BIM Kapsamı ve Hedefleri
### Referans Standartlar ve Dokümanlar
Projede BIM Uygulama Planı'nda tarif edilecek uygulama kapsam ve süreçlerine esas olan sözleşme maddeleri ile referans dokümanları burada özetlenecektir.

### Hedeflenen BIM Uygulamaları
BIM Uygulama Planı'nı hazırlayan tarafın, sözleşmesel kapsamla birlikte kendi süreçlerine yönelik hangi uygulamaları yapmayı amaçladığı listelenecektir.

## Görevler ve Sorumluluklar
### Proje Paydaşları İletişim Listesi
BIM uygulamalarının tüm süreç paydaşlarının iletişim bilgileri listelenecektir.

:Proje paydaşları iletişim listesi

| Adı Soyadı| Görevi | Firma | İletişim |
|------|-----|---------|------|
|    |   |    |    |
|    |   |    |    |

### Görev Tanımları ve Sorumlulukları
Bu bölümde BIM süreçleriyle ilgili çalışan pozisyonlarının tarifi ve sorumlulukları belirlenir. Aşağıdaki pozisyon isim ve tanımları proje kapsam ve sözleşme şartlarına göre farklı olabilir. Sorumluluk tablosunda geçen tüm görev tanımları aşağıdaki bölümde yer almalıdır.

#### BIM Yöneticisinin Sorumlulukları

#### Bilgi Yöneticisinin Sorumlulukları

#### BIM Koordinatörün Sorumlulukları

#### BIM Modelleyicilerin Sorumlulukları

### Organizasyon Yapısı
Proje yönetiminden başlayarak, BIM süreçlerine dahil tüm pozisyonların ağaç yapısıyla organizasyon şeması paylaşılacaktır.

##	BIM Süreçleri
Modellerin ana atanan, teslim ve iş ekipleri arasında, proje boyunca geliştirilmesi ve tüketilmesiyle ilgili tüm süreçler açıkça tanımlanacaktır.

### BIM Süreçlerine Yönelik Yapılacak Çalışma Toplantıları ve Eğitimler
Süreçlerin geliştirilmesiyle ilgili paydaşların yapacağı farklı çalışma toplantıları, bu süreçlerin pekişmesini sağlamak ve/veya sözleşme şartları gereği yapılacak eğitimlerin tanımlanmaları yapılacaktır.

### BIM Modelleme ve Koordinasyon Süreçleri
Modellerin oluşturulması ve koordinasyonu için, gerekli detayda, adım adım tüm aşamaların görsel iş akış şemalarıyla desteklenerek net bir şekilde tarifi yapılacaktır. Sorumluluk tablosunda yer alan paydaşlarla tutarlı bir şekilde süreç boyunca paydaşların işleri açıkça ifade edilecektir.

### Disiplinler Arası Koordinasyon ve Çakışma Süreçleri
Disiplinler arasındaki koordinasyon süreçleri ve bunu destekleyen model çakışma süreçleri için, gerekli detayda, adım adım tüm aşamaların görsel iş akış şemalarıyla desteklenerek net bir şekilde tarifi yapılacaktır. Süreç boyunca, sorumluluk tablosunda yer alan paydaşların işleri açıkça ve tutarlı bir şeklide ifade edilecektir.

### BIM Modellerinden İki Boyutlu (2b) Çizim Oluşturma Süreçleri
Model oluşturma süreçleriyle uyumlu olarak bu modellerden iki boyutlu (2b) çizim oluşturma süreçleri için, gerekli detayda, adım adım tüm aşamaların görsel iş akış şemalarıyla desteklenerek net bir şekilde tarifi yapılacaktır. Süreç boyunca, sorumluluk tablosunda yer alan paydaşların işleri açıkça ve tutarlı bir şeklide ifade edilecektir. Oluşturulan (2b) çizim için takip edilecek ulusal, kurumsal, veya proje özelindeki çizim CAD standardı belirtilerek, kullanılan yazılımlara uygun ayarlar, dosyalar ve referans dokümanlarına atıfta bulunulabilir.

### Model Kalite Kontrol Süreçleri
Modellerin içerik ve uygulama planına uygunluğu için kalite kontrol süreçleri ile yapılan kontrollerin belgelendirilmesi amacıyla @sec-bim-plan-ek1 bölümünde tanımlanan formun nasıl kullanılacağı tarif edilecektir.

### Görselleştirme
Modellerden toplantı, rapor vs. için oluşturulacak görseller ile ilgili gerekli beklentiler ve bilgiler verilecektir.

### BIM Modellerin Saha Durumuyla Güncelleştirilmesi (As-built)
Kapsamda bulunması halinde, modellerin proje sonunda sahada gerçekleştirilen haliyle uyumlu olarak güncelleştirilmesinin yöntemi, süreci ve belgelendirilmesi tarif edilecektir.

## BIM Modellemesi için Gereksinimler

### Modelde Kullanılacak Dil(ler)
Model içeriğinde kullanılacak dil tanımlanacaktır. Eğer birden fazla dil kullanılacaksa, iki dilin bir arada hangi şartlarda kullanılacağı tarif edilecektir.

### Birimler & Koordinatlar

#### Ölçü Birimleri
Modeleme için kullanılacak temel ölçü birimleri verilecektir. Kullanılan yazılım(lar) için gerekli ayarlamalar tarif edilebilir veya yapılandırma (konfigürasyon) dosyası verilebilir.

#### Proje Referans Koordinatları
Modeleme için kullanılacak referans koordinatlar ile projedeki referans noktanın konumu tanımlanacaktır. Projenin farklı yazılımlarda doğru olarak yerleştirilmesi için kullanılan coğrafi koordinat sistemi verilmelidir. Kullanılan yazılım(lar) için gerekli ayarlamalar tarif edilebilir veya yapılandırma (konfigürasyon) dosyası verilebilir.

#### Proje Referans Kot Seviyeleri
Modeleme için kullanılacak referans kat kotları verilecektir. Doğru tanımlama yapılması için, verilen kotların nereye göre verildiği ve mutlak ve/veya göreceli olarak ölçüldüğü açıkça tarif edilmelidir.

### Model İçerikleri ve Eleman Bilgi Gereksinimleri
Alt başlıklarda belirtilen kapsamlar için modelde dahil edilecek elemanların dökümü yapılacaktır. Proje şartnamesinin @sec-bilgi-model-içerikleri bölümünde belirtilen elemanlarla birlikte, koordinasyon ve simülasyon gibi tariflenen BIM hedeflerine yönelik modellenecek diğer tüm elemanlar belirtilecektir. Modellenecek elemanlar ile birlikte modelde dahil edilmeyecek elemanlar belirtilecektir. Model içinde dahil edilecek elemanların dökümü, detay seviyeleri ve hazırlanmasından sorumlu paydaşları [@sec-bim-plan-ek3]'da verilecektir.

#### Mimari Elemanlar
#### Yapısal Elemanlar
#### Havalandırma Sistemleri Elemanları
#### Elektrik ve Bilişim Sistemleri Elemanları
#### Sıhhi Tesisat ve Yangın Koruma Sistemleri Elemanları
#### İnşaat ve Altyapı Elemanları
#### Özel Sistemler ve Elemanları
#### Diğer Elemanlar

### Model İçerik Adlandırmaları

#### Model Dosya Adlandırması
Model dosyaların adlandırma kuralları tarif edilecektir. Her bir modelin özgün olarak tanımlanmasını sağlayacak farklı isim katmanlarıyla, tutarlı olarak yapılandırmak gerekmektedir. Adlandırmada disiplin, sistem, kat, bölge vb. değişik özellikleri tanımlayacak katmanlar için kullanılan kodlamalar bilgi kapları kodlamalarıyla tutarlı olacaktır. Proje boyunca oluşturulan modeller Model Dosyaları Listesi'nde güncel tutulan bir ek olarak paylaşılacaktır.

#### Malzeme Adlandırması
Modellerde kullanılan malzeme tanımlarının adlandırma kuralları tarif edilecektir. Her bir malzeme türünün özgün olarak tanımlanmasını sağlayacak farklı isim katmanlarıyla, tutarlı olarak yapılandırılması gerekmektedir.

#### Model Görüntülerin Adlandırması
Modellerde oluşturulan farklı görüntülerin adlandırma kuralları tarif edilecektir. Her bir görünümün özgün olarak tanımlanmasını sağlayacak farklı ve tutarlı olarak yapılandırılması gerekmektedir.

#### Çalışma Gruplarının Adlandırması
Modelleri oluştururken ve/veya kullanılırken eleman, sistem ve disiplin vb. bazında oluşturulan gruplar ve adlandırmalar tarif edilecektir. Her bir grubun özgün olarak tanımlanmasını sağlayacak farklı ve tutarlı olarak yapılandırılması gerekmektedir.

### Model Dosya Şablonu
Oluşturulacak model dosyaları için kullanılacak yapılandırma (configuration) verileri ile referans içerikleri bulunduran dosya şablonu verilecektir.

### Model İçerik Renklendirme Düzeni
Modellenen elemanlara nasıl renk verileceği tarif edilecektir. Renklerin disiplin veya eleman bazında, eleman veya malzeme aracılığıyla nasıl renklendirileceği detaylandırılmalıdır.

### Diğer Gereksinimler
Verilen başlıklar dışında, varsa diğer genel gereksinimlere burada yer verilebilir.

### BIM Model Yapılanması
Bir araya geldiğinde bir bütün olarak projeyi tarifleyen BIM model dosyalarının nasıl bölümleneceği tarif edilecektir. Projenin boyutu ve yapısına uygun olarak ayrı bölümler, katlar ve disiplineler için ayrı BIM model dosyaları oluşturulabilir. Gerekli olması halinde, tüm paydaşların BIM modellerle sorunsuz bir şekilde çalışmasını sağlamak amacıyla, dosya boyutu gibi, belli koşullar tarif edilebilir.

### Diğer Gereksinimler
Verilen başlıklar dışında, varsa diğer genel gereksinimlere burada yer verilebilir.

## İletişim ve Teslim Kuralları
Proje boyunca tanımlanan kapsamların yerine getirilmesi için gerekli süreçler ve süreç sahiplerinin işbirliği içinde nasıl çalışacağı tanımlanacaktır.

### Resmi İletişim Yöntemleri
Proje paydaşları arasındaki iletişim süreci ve yöntemleri tarif edilecektir. İletişimin hangi paydaşlar arasında gerçekleşeceği ile birlikte, belli paydaşlarla formal süreçler dışında gerçekleşmemesi gereken iletişimler tanımlanacaktır.

### Yapılacak Toplantılar
İlgili her proje aşamasında paydaşlar arasında yapılacak toplantılar tanımlanacaktır. Proje başında ve sonunda periyodik olarak yapılması gereken toplantılarla, bu toplantıların hangi paydaşlar arasında ve hangi sıklıkta yapılacağı ile katılım zorunlulukları tarif edilecektir.

### Teslim Edilecek BIM Çıktıları
BIM süreçleriyle elde edilen model ve veri çıktılarının, hangi aşamalarda, hangi formatlarda, nasıl iletileceği tarif edilecektir. Teslimlerin tanımlanması @sec-bim-plan-ek5 ile yapılacaktır. Bu döküm aracılığıyla bilgi üretimi ve onaylar için gerekli iş yükü tanımlanacaktır. Her iş ekibin kendi kapsamıyla ilgili oluşturulan planlama dökümlerine teslim tarihlerinin eklenmesiyle İş Bilgi Teslim Planları'nın (İBTP) biraraya getirilmesiyle Ana Bilgi Teslim Planı (ABTP) proje boyunca güncellenerek takip edilecektir. İBTP ve ABTP için Ek 6'da planlama şablonuyla örnek plan verilmektedir.

### Resmi Doküman ve Model Teslim Kuralları
Sözleşmede tanımlanmış tüm belge ve modellerin projede kullanılan ortak veri ortamı üzerinden hangi sıklıkta ve formatlarda, kimlerle paylaşılacağı tarif edilecektir.

### Resmi Olmayan Gündelik Doküman ve Model Paylaşım Kuralları
Gündelik çalışmalar sırasında iş ekiplerinin içinde veya ekiplerın aralarında, projede tanımlı olmayan teslimler ve doğacak ihtiyaçlar için resmi olmayan iletişimler ile yöntemler paylaşılacaktır.

## Teknoloji ve Donanım Altyapısı
BIM süreçlerinin gerçeklenmesi için gerekli tüm teknoloji ve donanım altyapısı tarif edilecektir.Kullanılacak donanımlar (bilgisayar, sunucular ve bulut tabanlı servisler), ortak veri ortamı, yazılımlar ile sürümleri listelenecektir. Uzun sürecek projelerde gerekli görülmesi halinde hangi sıklıkta ve yöntemle sürüm güncellemeleri yapılacağı tarif edilebilir.

## BIM Uygulama Planı Ekleri

### Ek 1 Model Kalite Kontrol Formları
BIM modellerinin teslimiyle beraber, kontrollerin modelleri hazırlayanlardan farklı kişiler tarafından yapıldığının belgelendiği formlar iletilecektir. Bu yapılan kontrolle, hazırlanan BIM modellerinin proje BIM Şartnamesi, BIM Uygulama Planı ve BIM Standardı'na uygunluğu kontrol edilecektir ve gerekli uygunsuzlukların tespit edilip düzeltilmesi sağlanacaktır. Kalite kontrollerinin projede hangi aşamalarda kimler tarafından yapılacağı proje BIM Uygulama Planı'nda ve BIM Modelleri Oluşturma Süreç ve Yöntemleri ekinde tanımlanacaktır. Örnek model kalite kontrol formları, rehberin @sec-bim-plan-örnek bölümünde, @sec-bim-plan-ek1 olarak verilmiştir.

### Ek 2 Model İçerik Oluşturmada Kullanılan Kaynak Takip Listesi
BIM modellerinin hazırlanması sırasında referans olarak kullanılan çizimler ve belgeler gibi kaynakların belgelenmesi için listeler tutulacaktır. Bu liste ayrı bir belge veya model dosyasının içinde bir tablo olarak paylaşılabilir. Model içeriklerinin doğruluğu, güncelliği ve/veya amacına uygunluğunun teyit ve takip edilebilmesi bakımından gereklidir. Örnek kaynak takip listesi formu, rehberin @sec-bim-plan-örnek bölümünde, @sec-bim-plan-ek2 olarak verilmiştir.

### Ek 3 Model Eleman Bilgi Gereksinimleri Tablosu
Projedeki BIM hedeflerine yönelik modele dahil edilecek elemanların dökümü yapılacaktır. Farklı aşamalarda modellere dahil edilecek elemanlar, detay seviyeleri ve parametreleri verilecektir. Model eleman bilgi gereksinimleri tablosu şablonu ve örneği, rehberin @sec-bim-plan-örnek bölümünde, @sec-bim-plan-ek3 olarak verilmiştir.

### Ek 4 Model Dosyaları Listesi
Proje kapsam ve yapısına uygun şekilde bölge, bina, kat, disiplin gibi gruplamalara göre BIM modellerin nasıl ayrılacağı listelenecektir. BIM modelleri projede belirlenen isimlendirmelere uygun olarak listelenip, ayrımları çizim veya görsellerle, farklı renklendirmelerle gösterilebilir.

### Ek 5 BIM Modelleri ve Bilgi Teslim Planlama Dökümü
Farklı yapı geliştirme aşamalarında üretilecek bilgi kaplarına dair üst başlıkların belirlenmesi ile bilgi alışverişi sürecinin anlaşılır bir şekilde planlanması ve ileride yaşanması muhtemel sorumluluk, bilgi üretim ve değişim karmaşasının engellenmesi amaçlanmaktadır. Örnek teslim planlama döküm şablonu, rehberin @sec-bim-plan-örnek bölümünde, @sec-bim-plan-ek5 olarak verilmiştir.
Teslim planı öncesi bilgi kaplarının üst ölçekten üretim kapsamlarının ve sayılarının belirlenmesine yönelik doldurulacaktır. Ekte mimari bilgi kabı örnek olarak veirlmektedir.

### Ek 6 BIM Modelleri ve Bilgi Teslim Planı (İBTP, ABTP)
Projede görev alan teslim ve iş ekipleri tarafından oluşturulacak tüm bilgi modellerinin listesi ve teslim tarihlerinin planlandığı dökümler hazırlanacaktır. Her iş ekibinin kendi kapsamındaki bilgi modellerinin dökümünü ve teslim tarihlerinin listelendiği İş Bilgi Teslim Planları (İBTP) derlenerek, tüm projenin bilgi modellerinin dökümü ve teslim tarihlerinin takip edilebildiği Ana Bilgi Teslim Planı (ABTP) oluşturulur. Bu planlar proje fazlarıyla uyumlu olarak hazırlanıp, proje boyunca güncellenerek, iş ekiplerinin ilerlemelerinin ve projelerin takibi için kullanılacaktır. Örnek teslim planı şablonu, rehberin @sec-bim-plan-örnek bölümünde, @sec-bim-plan-ek6 olarak verilmiştir.

### Ek 7 BIM Stardardı
İşveren ve/veya ana atayan taraf, projede BIM modellerinin hazırlanmasında takip edilecek modelleme standartlarını tanımlayacaktır. Kurumsal BIM Modelleme Standardı bulunmaması durumunda yüklenici(ler) tarafından teslim gereksinimlerine ve kullanım amaçlarına uygun bir şekilde hazırlanması talep edilecektir.

### Ek 8 BIM Modelleri Oluşturma Süreç ve Yöntemleri
BIM modellerini oluşturmak için tanımlanan süreci görsel iş akışı olarak adım adım tarif eden şema(lar) hazırlanacaktır. Modellerin oluşturulması sürecindeki: referans bilgi kaynaklarının sağlanması, modellerin kalite kontrolünün yapılması, onaylanması, düzeltmelerin yapılması, paydaşlar arasında teslimlerin yapılması, modelden bilgilerin çekilmesi dahil; her adım iş akışında gösterilecektir.

### Ek 9 BIM Modellerinden Pafta Oluşturma Süreç ve Yöntemleri
BIM modelleriyle 2b paftaların oluşturulması için tanımlanan süreci görsel iş akışı olarak adım adım tarif eden şema(lar) hazırlanacaktır. Ayrıca modellerden paftaların oluşturulmasında kullanılan yazılımlar, ayarları ve varsa şablonlar tarif edilecektir.

### Ek 10 BIM Modelleriyle Proje Planlama (4b) Simülasyon Oluşturma Süreç ve Yöntemleri
BIM modelleriyle proje planlama (4b) simülasyonlarının oluşturulması için tanımlanan süreci görsel iş akışı olarak adım adım tarif eden şema(lar) hazırlanacaktır. Ayrıca modellerle proje planlama (4b) simülasyonlarıyla raporlamaların oluşturulmasında kullanılan yazılımlar ve ayarları tarif edilecektir.

### Ek 11 BIM Modellerinin Saha Durumuyla Güncelleştirilmesi Süreç ve Yöntemleri
Proje sırasında tasarımdaki talep ve koordinasyon ile teslim kontrollerinde yapılan düzeltmeler sonucundaki değişikliklerin BIM modellerine aktarılması için tanımlanan süreci görsel iş akışı olarak adım adım tarif eden şema(lar) hazırlanacaktır. Değişikliklerin sahadan doğrudan takip edilmesi veya saha rapor ve belgelerden dolaylı olarak takip edilmesi için gerekenler ve sorumlu paydaşlar tarif edilecektir. Kayıt modellerinin oluşturulması için farklı ek süreçler de tarif edilmesi gerekebilir.

### Ek 12 BIM Süreçlerinde Takip Edilen Ana Performans Göstergeleri
Projede BIM uygulamalarının takibi ve planlanması gibi farklı amaçlara yönelik anahtar performans göstergelerinin tanımı ve takibin nasıl yapılacağı tarif edilecektir. Başlıca göstergeler modelleme üretkenliği, model kalitesi, pafta üretimi, koordinasyon problemlerinin takibi konusunda belirlenebilir.


