# IV Yükleniciler için bSTR BIM Uygulama Planı Rehberi {.unnumbered}

| | |
|-|--------------|
|**Hazırlayan:**| Standartlar & Yayınlar Çalışma Grubu |
|**Tarih:**|29.09.2022     |
|**Versiyon:**|00     |

&nbsp;

Bu bölüm, projelerini sayısal süreçler ve BIM araçları kullanarak yürütecek tasarım ve uygulama yüklenicileri için hazırlanmıştır. Bölüm 3 *İşverenler ve İşletmeciler için bSTR BIM Teknik Şartname Rehberi *'nde tarif edilen BIM Teknik Şartnamesi'yle uyumlu bir şekilde, yüklenici paydaşların yer alacağı süreçlerle, hazırlayacakları içeriklerin tanımlanması ve planlanması için gerekli belgelerin oluşturulmasını tarifler. Bu bölümden faydalanacak yükleniciler, kendi proje kapsamlarında işveren tarafından hazırlanan şartnamelere ve tanımlanan ilgili gereksinimlerle uyumlu olarak kendi BIM Uygulama Planı'nı oluşturacaktır. TS EN ISO 19650-2 inşaat projesi bilgi yönetimi sürecinde teklif hazırlığı aşamasında, olası ana atanan tarafın, çalışacağı bir veya birden fazla olası iş ekibiyle beraber atama öncesi BIM Uygulama Planı hazırlaması gerekmektedir. Proje ataması yapılan ana atanan taraf, iş ekipleriyle beraber, teklif sürecinde hazırlandıkları BIM Uygulama Planı'nı güncelleyip projeye başlamadan önce teyit eder.

&nbsp;

Editör
: Dr. Ahmet ÇITIPITIOĞLU, *bSTR Standartlar ve Yayınlar Çalışma Grubu Koordinatörü (TAV İnşaat)*

&nbsp;

**Katkıda Bulunanlar**

Çalışma grubu bünyesinde taslak hazırlanmasına destek olan ve hazırlanan taslaklara görüş, yorum ve tekliflerini ileten, konu hakkında
tecrübelerini paylaşan uzman gönüllülerimize teşekkür ederiz.


##### STANDARTLAR ve YAYINLAR ÇALIŞMA GRUBU İCRA KURULU#
| | |
|---|---|
| Dr. Ahmet ÇITIPITIOĞLU, *TAV İnşaat* | Öncü Ceren Varol ALİCİK, *Sika* |
| Yrd. Doç. Dr. Aslı Akçamete GÜNGÖR, *ODTÜ* | Osman ÖZKAN, *EAE Elektrik* |
| Aygen ERKAL, *Türkiye İMSAD* | Prof. Dr. Salih OFLUOĞLU, *ABÜ* |
| Bahadır DEMİRTAŞ, *Arup* | Serdar BİRDEN, *BIMMade* |
| Behnam AGHBALİ, *Saina* | Serhat KAŞ, *Yüksel Proje* |
| Berke ÇELİKEL, *Freelance* | Serkan ELİBOLLAR, *ProCS* |
| Çağdaş Ilgaz ŞENEL, *Hilti* | Uğur KAYA, *Emay* |
| Prof. Dr. Esin Ergen PEHLEVAN, *İTÜ* | Utku BAŞYAZICI, *Doxa87* |
| İdris BAHADUR, *Saina* | Yudum DEMİRKOL, *Şişecam* |
| Melis ATAY, *Turner* | |

&nbsp;

**Görüş Verenler**

| | |
|---|---|
| Burcu Esen BARUTÇU, *Drees & Sommer* | |
