# V Malzeme Üreticileri için bSTR BIM Yol Haritası {.unnumbered}

| | |
|-|--------------|
|**Hazırlayan:**| Proje Geliştirme Çalışma Grubu |
|**Tarih:**|11.11.2022 |
|**Versiyon:**|00     |

&nbsp;

Dünya çapında inşaat sektörü sayısallaşırken, inşaat malzemesi üreticilerinin de bu akıma katılması ve sürece katkı sağlaması gerekmektedir. İnşaat sektöründe sayısallaşmanın anahtarlarından olan BIM (Yapı Bilgi Modellemesi) yaklaşımının benimsenmesinde malzeme üreticileri de diğer sektör paydaşları gibi bazı çalışmalar yürütmelidir.

BIM modeli fiziki binanın sanal bir prototipidir. Bu prototipin gerçekliği, içermiş olduğu gerçek ürün bilgileri ile güçlenir. Üreticilerin ürünleri ile ilgili bilgileri paylaşmaları ve projelerde bu bilgilerin kullanılması BIM'in yaygınlaşması için çok önemlidir. Üretici tarafından sağlanan bilgiler sayesinde hatalı veri girişleri önlenir ve tesis yönetimi gibi alfasayısal veriye en çok ihtiyaç duyulan evreler için önemli faydalar sağlanabilir.

Türkiye'deki inşaat malzemesi üreticileri, Türk ekonomisinde ihracata katkı sağlayan ana paydaşlardandır ve yurtdışı pazarlarında BIM'in benimsenmesindeki artışla birlikte, Türkiye'deki üreticilerden de hem yurt dışından hem de yurt içinden BIM içerikleri talep edilmeye başlanmıştır.  Bu üreticilerin BIM'i benimsemesi ve müşterilerine BIM nesneleri sağlamaları ile yurt dışı pazarlarda daha iyi rekabet etmeleri, sayısallaşmanın etkisi ile iç süreçlerindeki verimsizlikleri gidermeleri ve Türk ekonomisine katkı sağlamaları beklenmektedir.

Ancak birçok üretici firma bu süreci nasıl yürütebileceği konusunda bilgi sahibi değildir. Rehberimn bu bölümünün amacı, malzeme üreticilerinin BIM'i benimseme sürecinde BIM içeriklerinin geliştirilmesinde ve sunulmasında karşılaştıkları sorunlar ile genel eğilimlerin tespit edilmesi ve buna dayanarak BIM'in bu süreçte üretici firmalara rehberlik edebilecek öneriler geliştirmektir.

&nbsp;

Editör
: Serkan Elibollar, bSTR Proje Geliştirme Çalışma Grubu Koordinatörü (ProCS)

&nbsp;

**Katkıda Bulunanlar**

Bu bölümün hazırlanması amacına da destek vermesi amacıyla başlatılan Sn. Kerim Kaan KARAKOÇ'un yüksek lisans tezi çalışması sonuçları bu bölümde doğrudan kullanılmıştır. Bu sebeple tezi hazırlayan Sn. Kerim Kaan KARAKOÇ'a, tez danışmanı Prof. Dr. Esin Ergen PEHLEVAN'a ve sektörel tecrübelerini tez çalışmalarında kullandırarak katkı sağlayan Serkan ELİBOLLAR’a teşekkür ederiz.

Çalışma grubu bünyesinde taslak hazırlanmasına destek olan ve hazırlanan taslaklara görüş, yorum ve tekliflerini ileten, konu hakkında tecrübelerini paylaşan uzman gönüllülerimize teşekkür ederiz.

&nbsp;

**Görüş Verenler**

| | |
|---|---|
|Prof. Dr. Salih OFLUOĞLU, *ABÜ* | |
