# Önsöz {.unnumbered}

Muhammed Maraşlı
: buildingSMART Türkiye Yürütme Kurulu Başkanı

Dünyada kullanımı son 15 yılda hızla yayılan BIM ile inşaat ve yapı sektörü; hız, verimlilik, sürdürülebilirlik ve ekip çalışması avantajlarına kavuşuyor. Dolayısıyla BIM’in önemi, hem yurt dışındaki projelerdeki gereksinimler hem de Türkiye’de sektörün bu yönde evrilmesi doğrultusunda her geçen gün artıyor. Yurt dışı müteahhitlik hizmetlerinde ilk üç sıra içinde yer alan Türk müteahhitlerin daha fazla değer yaratması adına istihdam, malzeme ve projelerin de birlikte hareket etmesi için özel sektörün yanı sıra kamu kuruluşlarının da BIM uygulamalarına yönelik desteğinin sağlanması gerekli görünüyor.

Ülkemizde BIM kullanımı konusunda hala yolun başında olduğumuzu biliyoruz. Ama yine de birçok önemli projede BIM kullanıldığını; mimar, mühendis, müteahhit ve müşavirlerimizin bu konudaki çabalarını görmek sevindirici. Kamudaki sözleşmelerin bazılarında BIM zorunluluğunun getirilmesi de ülkemizdeki projelerde BIM kullanım oranını artırdı. Diğer bazı ülkelerde olduğu gibi ülkemizde de tüm kamu kurumlarının belli büyüklükteki projelerde BIM kullanımını zorunlu hale getirmesi süreci daha da hızlandıracaktır. Büyük ölçekli firmalar BIM’e ciddi yatırım yaparken küçük ölçekli firmalarda da BIM’e geçiş konusunda bir gayret söz konusu. Fakat BIM’e tam anlamda geçiş için sadece finansal kaynaklar değil ciddi bir süreçe ve bilince ihtiyaç var. Bunun yanı sıra eğitim, araştırma ve üniversite-sanayi işbirliği çerçevesinde pek çok çalışma yürütüldüğünü biliyoruz.

Ülkemizde bu konuda yapılacak çok fazla görev ve sorumluluk olduğu bilincinden hareketle; inşaat sektörünün tüm paydaşlarının ortak çabasıyla kurulan buildingSMART Türkiye, tüm yapı sektörü paydaşlarının yapıların yaşam döngüsü boyunca iş süreçlerini iyileştirmeye yönelik veri oluşturma, verinin ortak paylaşımını sağlama ve güncelleme konusunda anlayış birliği ve iş metotları geliştirmiş bir Türkiye yapı sektörü yaratma vizyonuyla çalışmalarını yürütüyor. buildingSMART Türkiye olarak misyonumuz yapı sektörü paydaşlarının açık standartlarla, işbirlikçi süreçler ve bileşik uygulamalarla çalışmasını sağlamaya yönelik açık işbirliği ve iletişim ortamını sağlayan bir odak olarak; üyelerine destek, öğrenim fırsatları ve iyi örnek uygulamaları sunarken buildingSMART International çalışmalarına katkıda bulunmaktır.

Bu çalışmayla sektörümüzün tüm paydaşların kendi çalışma alanlarıyla ilgili yapının tüm yaşam döngüsün boyunca üretilen bilgilerin düzenlenmesi, sayısallaştırılması ve yönetilmesi konusunda uzun zamandır talep edilen bu rehberi yayınlamaktan büyük bir mutluluk duyuyoruz.

Birçok buildingSMART Türkiye üyemiz bu çalışmaya katkıda bulundu. Titiz çalışmalarından dolayı başta buildingSMART Türkiye Yürütme Kurulu Başkan Yardımcısı ve Standartlar ve Yayınlar Çalışma Grubu Koordinatörü Dr. Ahmet Çıtıpıtıoğlu ile buildingSMART Türkiye Yürütme Kurulu Üyesi ve Proje Geliştirme Çalışma Grubu Koordinatörü Serkan Elibollar’a, emeği geçen tüm üyelerimize buildingSMART Türkiye adına teşekkür ediyoruz. Çalışmalarımız konusunda daha detaylı bilgi edinmek ve çalışma gruplarımıza katılmak için web sitemizi ziyaret edebilirsiniz: www.buildingsmartturkiye.org

Gelin yapı sektörünün sayısal geleceğini beraber kurgulayalım…
